---
- name: Install Clickhouse
  hosts: yc-clickhouse
  roles:
    - clickhouse

- name: Install latest Vector
  hosts: yc-vector
  roles:
    - vector-role

- name: Install nginx
  hosts: yc-lighthouse
  handlers:
    - name: reload-nginx
      become: true
      ansible.builtin.command: nginx -s reload
  tasks:
    - name: Nginx - Install nginx
      become: true
      ansible.builtin.apt:
        name: nginx-full
        state: present
      notify: reload-nginx
    - name: Nginx - create config file
      become: true
      ansible.builtin.template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        mode: "a+r,u+rw,g+rw"
      notify: reload-nginx
    - name: Flush handlers
      ansible.builtin.meta: flush_handlers

- name: Install git for lighthouse
  hosts: yc-lighthouse
  tasks:
    - name: Lighthouse - install git
      become: true
      ansible.builtin.apt:
        name: git
        state: present

- name: Install lighthouse
  hosts: yc-lighthouse
  roles:
    - lighthouse-role
